services:
  percona-db:
    image: percona/percona-server:latest
    container_name: percona-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dbname
      MYSQL_USER: user1
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=car_sharing
    ports:
      - 5513:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  my-db:
    driver: local
  postgres:
    driver: local
    
